<h1>Статьи</h1>
<div><a href="<?php print $this->url('admin/article',array('action' => 'add'))?>">Добавить статью</a></div>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
&times;
</button><ul><li>')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

print $flash->render('success', array('alert','alert-dismissable','alert-success'));
print $flash->render('info', array('alert','alert-dismissable','alert-info'));
print $flash->render('default', array('alert','alert-dismissable','alert-default'));
print $flash->render('error', array('alert','alert-dismissable','alert-danger'));
?>
<table class="table table-striped table-hover">
    <tr>
        <td>#</td>
        <td>Категория</td>
        <td>Заголовок</td>
        <td>Статья</td>
        <td>Начало статьи</td>
        <td>Опубликовано</td>
        <td>Действие</td>
        <?php foreach($articles as $item):?>
            <?php $category =  $item->getCategory();
            if($category){
                $catName = $category->getCategoryName();
            }else{
                $catName = '';
            }
            if($item->getIsPublic()){
                $ispublic = "Опубликована";
            }else{
                $ispublic = "Неопубликована";
            }
            ?>
            <tr>
            <td><?php print $item->getId();?></td>
            <td><?php print $catName;?></td>
            <td><?php print $item->getTitle();?></td>
            <td><?php print $item->getArticleForTable();?></td>
            <td><?php print $item->getShortArticleforTable();?></td>
            <td><?php print $ispublic;?></td>
            <td>
                <a href='<?php print $this->url("admin/article",array("action" => "edit", "id" => $item->getId()));?>'>Редактировать</a>|
                <a href='<?php print $this->url("admin/article",array("action" => "delete", "id" => $item->getId()));?>'>Удалить</a>
            </td>
            </tr>
        <?php endforeach;?>

</table>

<?php
print $this->paginationControl($articles,'Sliding','pagination_control',array('route' => 'admin/article'));
?>
