<?php
if($this->pageCount):?>
<ul class="pagination pagination-sm">
    <?php if(isset($this->previos)):?>

     <li><a href="<?php print $this->url($this->route);?>?page=<?php print $this->previos;?>"> << </a></li>
    <?php else: ?>
        <li class="disabled"><a href="#" onclick="return false"> << </a></li>
    <?php endif;?>

    <?php foreach($this->pagesInRange as $page):?>
        <?php if($page != $this->current):?>
            <li><a href="<?php $this->url($this->route);?>?page=<?php print $page?>"><?php print $page?></a></li>
        <?php else:?>
       <li class="active"><a href="#"><?php print $page?></a></li>
        <?php endif;?>
    <?php endforeach;?>

    <?php if(isset($this->next)):?>
    <li><a href="<?php print $this->url($this->route);?>?page=<?php print $this->next?>"> >> </a></li>
        <?php else:?>
        <li class="disabled"><a href="#" onclick="return false"> >> </a></li>

    <?php endif;?>

</ul>
<?php endif; ?>
