<article>
    <div class="page-header">
        <h1 style="font-size: 2em;"><?php print $article->getTitle();?></h1>
    </div>
    <div class="panel-body">
        <p><?php print $article->getFullArticle();?></p>
    </div>
</article>
<div class="bs-docs-section">
    <div class="well">
        <?php $form->setAttribute('action',$this->url('blog',array('action' => 'comment')));?>
        <?php $form->setAttribute('class','form-horizontal');?>
        <?php $form->prepare();?>
        <?php print $this->form()->openTag($form);?>
        <fieldset>
            <legend>Добавить комментарий</legend>
        <div class="errors-comment"></div>
        <?php $email = $form->get('userEmail');?>
        <?php $email->setLabelAttributes(['class' => 'col-lg-2 control-label']);?>
            <div class="form-group">
                <?php print $this->formLabel($email)?>
                <div class="col-lg-10"><?php print $this->formEmail($email);?></div>
            </div>
        <?php $comment = $form->get('comment');?>
        <?php $comment->setLabelAttributes(['class' => 'col-lg-2 control-label']);?>
            <div class="form-group">
                <?php print $this->formLabel($comment)?>
                <div class="col-lg-10"><?php print $this->formTextarea($comment);?></div>
            </div>
       <input type="hidden" value="<?php print $article->getId();?>" name="arcticle"/>
        <?php print $this->formRow($form->get('submit'));?>
        <?php print $this->form()->closeTag($form);?>
        </fieldset>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $("form#comment").submit(function(){
            var formData = $("#comment").serialize();
            $.ajax({
                url : "/comment/",
                type: "post",
                dataType: "json",
                data: formData,
                success: function(data){
                    if(data['success'] == 1){
                        $('#new-comment-email h3').html($("#user_email").val());
                        $('#new-body-comment').html($("#user_comment").val());
                        $('#new-comment').show();

                        $(".bs-docs-section").hide('slow');
                        $(".no-comment").hide();
                    }else{
                        $('.errors-comment').html('');
                        for(var keys in data){
                            $('.errors-comment').append('<span>' + data[keys] + '</span>');
                        }
                    }
                }
            });
            setTimeout(function(){
                document.location = this.location;
            }, 4000)
            return false;
        });
    });
</script>

<?php $comments = $article->getComments();?>
<?php $count = $comments->count();?>
<?php if($count):?>
<h3>Комментарии(<?php print $count?>)</h3>
<?php foreach($comments as $comment):?>
<div class="panel-default">
    <div class="panel-heading">
        <?php print $comment->getUserEmail();?>
    </div>
    <div class="panel-body">
        <?php print $comment->getComment();?>
    </div>
</div>
<?php endforeach;?>
<?php else :?>
<h3 class="no-comment">Комментариев пока нет!</h3>
<?php endif;?>
<div id="new-comment" class="panel panel-success" style="display: none">
    <div id="new-comment-email" class="panel-heading">
        <h3 class="panel-title"></h3>
    </div>
    <div id="new-body-comment" class="panel-body"></div>
</div>