<h1>Категории</h1>
<div><a href="/admin/">На главную</a></div>
<div><a href="/admin/category/add/">Добавить категорию</a></div>
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
&times;
</button><ul><li>')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

print $flash->render('success', array('alert','alert-dismissable','alert-success'));
print $flash->render('info', array('alert','alert-dismissable','alert-info'));
print $flash->render('default', array('alert','alert-dismissable','alert-default'));
print $flash->render('error', array('alert','alert-dismissable','alert-danger'));
?>
<table class="table table-striped table-hover">
    <tr>
        <td>#</td>
        <td>Ключ</td>
        <td>Название</td>
        <td>Действие</td>
    </tr>
    <?php foreach($category as $item):?>
    <tr>

        <td><?php print $item->getId();?></td>
        <td><?php print $item->getCategoryKey();?></td>
        <td><?php print $item->getCategoryName();?></td>
        <td>
            <a href='<?php print $this->url("admin/category",array("action" => "edit", "id" => $item->getId()));?>'>Редактировать</a>|
            <a href='<?php print $this->url("admin/category",array("action" => "delete", "id" => $item->getId()));?>'>Удалить</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>