<table class="table">
    <tr>
        <th>Имя пользователя</th>
        <th>Пароль</th>
        <th>Email</th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->getUserName());?></td>
            <td><?php echo $this->escapeHtml($user->getUserPassword());?></td>
            <td><?php echo $this->escapeHtml($user->getUserEmail());?></td>
        </tr>
    <?php endforeach; ?>
</table>