<?php $user = $this->identity();?>
<?php if(empty($user)):?>
    <?php $form = $this->form;?>
    <?php $form->setAttributes(array('class' => 'form-inline'));?>
    <?php $form->prepare();?>
    <div class="row">
        <div class="col-lg-8" style="padding-top: 40px;">
            <?php echo $this->messages;?>
            <?php echo $this->form()->openTag($form);?>
            <?php $username = $form->get('userName');?>
            <?php $password = $form->get('userPassword');?>
            <div class="form-group">
                <?php echo $this->FormLabel($username);?>
                <?php echo $this->FormText($username);?>
            </div>
            <div class="form-group">
                <?php echo $this->FormLabel($password);?>
                <?php echo $this->FormPassword($password);?>
            </div>
            <?php echo $this->formRow($form->get('submit'));?>
            <?php echo $this->form()->closeTag($form);?>
            <p>Вход не выполнен!</p>
            <a href="<?php echo $this->url('auth-doctrine/default',array('controller' => 'index', 'action' => 'register'));?>">
                Регистрация
            </a>
        </div>
    </div>
<?php else:?>
    <div class="row">
        <div class="col-lg-12" style="padding-top: 40px;">
            <p>Авторизован как <?php echo $this->escapeHtml($user->getUserName());?></p>
            <div>
                <a href="<?php echo  $this->url('auth-doctrine/default',array('controller' => 'index', 'action' => 'logout'));?>">
                    Выйти
                </a>
            </div>
        </div>
    </div>
<?php endif;?>