<?php $user = $this->identity();?>
<?php if(empty($user)):?>
    <?php $form = $this->form;?>
    <?php $form->prepare();?>
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
&times;
</button><ul><li>')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

    print $flash->render('success', array('alert','alert-dismissable','alert-success'));
    print $flash->render('info', array('alert','alert-dismissable','alert-info'));
    print $flash->render('default', array('alert','alert-dismissable','alert-default'));
    print $flash->render('error', array('alert','alert-dismissable','alert-danger'));
    ?>
    <div class="row">
        <div class="col-lg-12" style="padding-top: 40px;">
            <a href="<?php echo $this->url('auth-doctrine/default',array('controller' => 'index', 'action' => 'register'));?>" class="btn btn-success">
                Регистрация
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8" style="padding-top: 40px;">
            <?php echo $this->form()->openTag($form);?>
            <?php $username = $form->get('userName');?>
            <?php $password = $form->get('userPassword');?>
            <div class="form-group">
                <?php echo $this->FormLabel($username);?>
                <div class="col-sm-4">
                    <?php echo $this->FormText($username);?>
                </div>
            </div>
            <div class="form-group">
                <?php echo $this->FormLabel($password);?>
                <div class="col-sm-4">
                    <?php echo $this->FormPassword($password);?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <?php echo $this->formRow($form->get('submit'));?>
                <div>
            </div>
            <?php echo $this->form()->closeTag($form);?>
        </div>
    </div>
</div>
<?php else:?>
    <div class="row">
        <div class="col-lg-12" style="padding-top: 40px;">
            <p>Авторизован как <?php echo $this->escapeHtml($user->getUserName());?></p>
            <div>
                <a href="<?php echo  $this->url('auth-doctrine/default',array('controller' => 'index', 'action' => 'logout'));?>">
                    Выйти
                </a>
            </div>
        </div>
    </div>
<?php endif;?>