<div class="bs-docs-section">
    <div class="well">
        <div class="comments_errors"></div>
        <?php
        $form->setattribute('action',$this->url('admin/comment',array('action' => 'edit', 'id' => $id)));
        $form->prepare();
        print $this->form()->openTag($form);
        print '<fieldset><legend>Редактирование комментария :</legend>';
        print '<div class="form-group">';
        print   '<label class="col-lg-10 control-label">Статья</label>';
        print   "<div class='col-lg-10'>{$comment->getArcticle()->getTitle()}</div>";
        print "</div>";


        print '<div class="form-group">';
        print   '<label class="col-lg-10 control-label">Email</label>';
        print   "<div class='col-lg-10'>{$this->formEmail($form->get('userEmail'))}</div>";
        print "</div>";



        print '<div class="form-group">';
        print  '<label class="col-lg-10 control-label">Comment</label>';
        print "<div class='col-lg-10'>{$this->formTextarea($form->get('comment'))}</div>";
        print '</div>';

        print "<div class='form-group'>";
        print "<input type='hidden' value='{$comment->getId()}'>";
        print "<div class='col-lg-10' style='margin-top: 15px;'>{$this->formRow($form->get('submit'))}</div>";
        print "</div>";
        print "</fieldset>";
        print $this->form()->closeTag($form);?>
    </div>
</div>