<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
&times;
</button><ul><li>')->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

print $flash->render('success', array('alert','alert-dismissable','alert-success'));
print $flash->render('info', array('alert','alert-dismissable','alert-info'));
print $flash->render('default', array('alert','alert-dismissable','alert-default'));
print $flash->render('error', array('alert','alert-dismissable','alert-danger'));
?>
    <table class="table table-striped table-hover">
        <tr>
            <td>#</td>
            <td>Статья</td>
            <td>Email</td>
            <td>Комментарий</td>
            <td>Действие</td>
            <?php foreach($comments as $item):?>
        <tr>
            <td><?php print $item->getId();?></td>
            <td><?php print $item->getArcticle()->getTitle();?></td>
            <td><?php print $item->getUserEmail();?></td>
            <td><?php print $item->getComment();?></td>
            <td>
                <a href='<?php print $this->url("admin/comment",array("action" => "edit", "id" => $item->getId()));?>'>Редактировать</a>|
                <a href='<?php print $this->url("admin/comment",array("action" => "delete", "id" => $item->getId()));?>'>Удалить</a>
            </td>
        </tr>
        <?php endforeach;?>

    </table>

<?php
print $this->paginationControl($comments,'Sliding','pagination_control',array('route' => 'admin/comment'));
?>